
"use client";

import React, { useState, useEffect, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth, Database, app } from "@/lib/firebase";
import { doc, getDoc, setDoc, onSnapshot } from "firebase/firestore";
import { getFunctions, httpsCallable } from "firebase/functions";

import { GameLayout } from "@/components/game/GameLayout";
import { CaseDisplay } from "@/components/game/CaseDisplay";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cases, type Case, type Puzzle } from "@/lib/cases";
import { cn } from "@/lib/utils";
import { ArrowRight, Loader2, Wand2 } from "lucide-react";
import { GenerateNewPuzzleInput, GenerateNewPuzzleOutput } from "@/lib/types";
import { HintButton } from "@/components/game/HintButton";


type GameState = {
  currentCaseIndex: number;
  currentPuzzleIndex: number;
  score: number;
  solvedPuzzles: string[];
  endlessPuzzles?: Puzzle[];
  hintedPuzzles?: string[];
};

const allSolutions = cases.flatMap(c => c.puzzles.map(p => p.solution));

const endlessCase: Case = {
    id: "case-endless",
    title: "Case ???: The Endless Hunt",
    description: "These missions are generated by the agency's AI. They are unpredictable and infinite. Good luck, agent.",
    puzzles: [],
};

const functions = getFunctions(app, 'us-central1');
const generateNewPuzzleFunction = httpsCallable<GenerateNewPuzzleInput, GenerateNewPuzzleOutput>(functions, 'generateNewPuzzle');


export default function CyberSleuthPage() {
  const [user, loading, error] = useAuthState(auth);
  const router = useRouter();
  const [gameState, setGameState] = useState<GameState | null>(null);
  const [userInput, setUserInput] = useState("");
  const [feedback, setFeedback] = useState<{ type: "correct" | "incorrect"; message: string } | null>(null);
  const [isPending, startTransition] = useTransition();
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    if (!loading && !user) {
      router.push('/');
    }
  }, [user, loading, router]);

  useEffect(() => {
    if (user) {
      const userDocRef = doc(Database, "users", user.uid);
      
      const unsubscribe = onSnapshot(userDocRef, (userDoc) => {
        if (userDoc.exists()) {
           const data = userDoc.data();
           setGameState({
              currentCaseIndex: data.currentCaseIndex ?? 0,
              currentPuzzleIndex: data.currentPuzzleIndex ?? 0,
              score: data.score ?? 0,
              solvedPuzzles: data.solvedPuzzles ?? [],
              endlessPuzzles: data.endlessPuzzles ?? [],
              hintedPuzzles: data.hintedPuzzles ?? [],
          });
        } else {
            console.log("User document not found, creating one.");
            const initialState: GameState & { email: string | null } = { 
                email: user.email,
                score: 0,
                solvedPuzzles: [],
                endlessPuzzles: [],
                hintedPuzzles: [],
                currentCaseIndex: 0,
                currentPuzzleIndex: 0,
            };
            setDoc(userDocRef, initialState).then(() => {
                 setGameState(initialState);
            });
        }
      });

      return () => unsubscribe();
    }
  }, [user]);

  const updateServerGameState = async (newState: Partial<GameState>) => {
      if (!user) return;
      startTransition(async () => {
        const userDocRef = doc(Database, "users", user.uid);
        await setDoc(userDocRef, newState, { merge: true });
      });
  }

  if (loading || !gameState || !user) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <Loader2 className="h-12 w-12 animate-spin" />
      </div>
    );
  }

  const isEndlessMode = gameState.currentCaseIndex >= cases.length;
  
  const currentCase: Case = isEndlessMode ? {...endlessCase, puzzles: gameState.endlessPuzzles || []} : cases[gameState.currentCaseIndex];
  const currentPuzzle: Puzzle | undefined = currentCase.puzzles[gameState.currentPuzzleIndex];
  
  const isPuzzleSolved = currentPuzzle ? gameState.solvedPuzzles.includes(currentPuzzle.id) : false;
  
  const handleNext = async () => {
    setFeedback(null);
    setUserInput("");

    if (!currentCase) return;

    const isLastPuzzleOfCase = gameState.currentPuzzleIndex >= currentCase.puzzles.length - 1;
    const isLastHandcraftedCase = gameState.currentCaseIndex >= cases.length - 1;

    if (isEndlessMode || (isLastPuzzleOfCase && isLastHandcraftedCase)) {
        // We are at the end, generate a new puzzle
        setIsGenerating(true);
        const lastCaseDesc = cases[cases.length-1].description;
        
        try {
            const result = await generateNewPuzzleFunction({
                lastCaseDescription: lastCaseDesc,
                existingSolutions: [...allSolutions, ...(gameState.endlessPuzzles?.map(p => p.solution) || [])]
            });
            
            const newPuzzle = result.data as any;

            if (newPuzzle) {
                const newPuzzles = [...(gameState.endlessPuzzles || []), newPuzzle];
                updateServerGameState({
                    currentCaseIndex: cases.length, // Set to endless mode index
                    currentPuzzleIndex: newPuzzles.length -1, // Go to the new puzzle
                    endlessPuzzles: newPuzzles,
                });
            } else {
                 setFeedback({ type: "incorrect", message: "Failed to generate a new mission." });
            }
        } catch (e) {
            console.error(e);
            setFeedback({ type: "incorrect", message: "An error occurred while generating a new mission." });
        } finally {
            setIsGenerating(false);
        }

    } else if (isLastPuzzleOfCase) {
        // Go to the next case
        updateServerGameState({ currentCaseIndex: gameState.currentCaseIndex + 1, currentPuzzleIndex: 0 });
    } else {
        // Go to the next puzzle
        updateServerGameState({ currentPuzzleIndex: gameState.currentPuzzleIndex + 1 });
    }
  };
  
  const handleHintUsed = () => {
    if (!currentPuzzle || !gameState || (gameState.hintedPuzzles || []).includes(currentPuzzle.id)) {
      return;
    }
    
    console.log("Hint used for the first time on this puzzle. Deducting points.");
    const newScore = Math.max(0, gameState.score - 10);
    const newHintedPuzzles = [...(gameState.hintedPuzzles || []), currentPuzzle.id];

    updateServerGameState({ 
      score: newScore,
      hintedPuzzles: newHintedPuzzles,
    });
  }

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!userInput.trim() || isPuzzleSolved || isPending || !currentPuzzle) return;

    if (userInput.trim().toLowerCase() === currentPuzzle.solution.toLowerCase()) {
      setFeedback({ type: "correct", message: `Correct! +${currentPuzzle.points} points` });
      
      const newGameState: Partial<GameState> = {
        score: gameState.score + currentPuzzle.points,
        solvedPuzzles: [...gameState.solvedPuzzles, currentPuzzle.id],
      };
      
      updateServerGameState(newGameState);

    } else {
      setFeedback({ type: "incorrect", message: "Incorrect. Try another approach." });
      const newScore = Math.max(0, gameState.score - 5);
      if (newScore !== gameState.score) {
          updateServerGameState({ score: newScore });
      }
    }
  };

  if (!currentPuzzle) {
    // This can happen if we are at the end of the handcrafted cases and need to generate a new one.
    return (
       <GameLayout
            caseTitle="Awaiting Orders..."
            caseDescription="Stand by for your next mission."
            score={gameState.score}
        >
            <div className="text-center p-8">
                <p className="text-lg mb-4">You have completed all available handcrafted missions.</p>
                <Button onClick={handleNext} disabled={isGenerating}>
                    {isGenerating ? 
                        <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Generating Mission...</> : 
                        <><Wand2 className="mr-2 h-4 w-4" />Request Next Mission</>
                    }
                </Button>
                 {feedback && <p className="text-red-400 text-sm mt-4">{feedback.message}</p>}
            </div>
        </GameLayout>
    )
  }

  return (
    <GameLayout
      caseTitle={currentCase.title}
      caseDescription={currentCase.description}
      score={gameState.score}
    >
      <CaseDisplay puzzle={currentPuzzle} />

      <div className="mt-6">
        <p className="text-muted-foreground font-code mb-2">{currentPuzzle.prompt}</p>
        <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row items-center gap-2">
          <Input
            type="text"
            value={userInput}
            onChange={(e) => setUserInput(e.target.value)}
            placeholder="Enter your answer..."
            className="font-code flex-grow"
            disabled={isPuzzleSolved || isPending}
            aria-label="Answer input"
          />
          <Button type="submit" disabled={isPuzzleSolved || isPending} className="w-full sm:w-auto">
            {isPending ? <Loader2 className="animate-spin" /> : "Submit"}
          </Button>
        </form>

        <div className="mt-4 h-12 flex items-center justify-between">
            {feedback && (
                <p className={cn(
                    "text-sm font-semibold transition-all duration-300",
                    feedback.type === 'correct' ? 'text-green-400' : 'text-red-400',
                )}>
                    {feedback.message}
                </p>
            )}
            
            {!isPuzzleSolved && <HintButton puzzle={currentPuzzle} onHintUsed={handleHintUsed} />}
            
            {isPuzzleSolved && (
                 <Button onClick={handleNext} variant="outline" className="ml-auto" disabled={isPending || isGenerating}>
                     {(isPending || isGenerating) && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                    Next Mission
                    <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
            )}
        </div>
        
      </div>
    </GameLayout>
  );
}
